### ISSUE TITLE
Add practice information to Rec program page

### ISSUE THREAD

**Issue by paysl-johnl** [paysl-johnl/paysl.org#44]
Rec program page: https://www.paysl.org/about-rec-soccer

Parents often ask about the practice schedule, so let's provide it on the program page.

**Comment by paysl-johnl** [comment]
Added a section with practice info to the About Rec page here: https://www.paysl.org/about-rec-soccer

Also added a link to the Frequently Asked Questions to that same page.

**Comment by paysl-briang** [comment]
Can be closed, reviewed and looks good..
