### ISSUE TITLE
Soccer rules by age or Laws of the Game

### ISSUE THREAD

**Issue by paysl-johnl** [paysl-johnl/paysl.org#67]
This could be helpful on the Recreational program page and the Coaching Resources page.

**Comment by paysl-briang** [comment]
Was pinged by a coach that he liked the new site but could not find the Laws of the Game page that was on the old site.  I also could not find it, then I saw it at the bottom of the page.  I added it FOR NOW to the navigation for Resources

**Comment by paysl-johnl** [comment]
@paysl-briang I like that. As for the rules by age, I like the simple chart that Wells Branch Soccer has here:
![image](https://user-images.githubusercontent.com/52214965/61722774-81d89100-ad30-11e9-9dd9-37d5f233110b.png)
It doesn't include ALL the rules, but the basics by age level which is kinda useful. I'm not sure how to do a table like this in squarespace (other than an image, which is a possibility).

**Comment by paysl-johnl** [comment]
@paysl-briang Maybe you could synthesize some of what Kevin provided in that document to put on the website?

https://3.basecamp.com/3791067/buckets/4202257/uploads/1982854399

**Comment by paysl-briang** [comment]
Added a matrix at the top of the page to show the "simple" rules.  Reviewed all of the laws for each age group and updated mostly 9U10U and a few laws in 7U8U.  Removed all of the references to dropped ball on temporary stoppage, updated offsides rules, updated build out line rules as it applits to goal kicks.  Still need to add substitution policies to all age groups, appears we do not have any guidance for when and how to substitute.

**Comment by paysl-briang** [comment]
Added in substitutions and further definition for build out line.   Also added in when headers are allowed, to the matrix at the top of the screen.
