### ISSUE TITLE
Should we take down the "Register Now" button from the homepage?

### ISSUE THREAD

**Issue by paysl-johnl** [paysl-johnl/paysl.org#95]
Now that registration is finished, should we remove that button? Thoughts?

**Comment by paysl-briang** [comment]
No leaving everything up is fine, that way we don't have to go back and add it later.  Added notes to the pages say registration is closed.  Got Soccer will block them anyway.

**Comment by paysl-johnl** [comment]
@paysl-briang Too late. I removed the button weeks ago. 😂

We can add it back when registration opens again next month.

**Comment by paysl-briang** [comment]
Well @paysl-johnl maybe you should have moved it to completed or add an updated comment....killin' me smalls!  You going to add a new issue to track adding it back....
