### ISSUE TITLE
Add a "Attend a Training" button to Select pages

### ISSUE THREAD

**Issue by paysl-johnl** [paysl-johnl/paysl.org#96]
Glenn mentioned that Fierce United had this feature on their site and we should add it ourselves:
![Screen Shot 2019-09-04 at 11.30.00 AM.png](https://images.zenhubusercontent.com/5d125fef7470440356e98ab3/fc9231a2-8884-4cdb-b833-26d0a30db7cb)

I'm thinking there's some text and a button that links to a page with a form to fill out that sends an email to Glenn.

**Comment by paysl-johnl** [comment]
@paysl-briang I added this feature here. Take a look. This could be a nice thing to add to the Academy page as well, driving them to attend an Academy Observation.

https://www.paysl.org/about-select

**Comment by paysl-briang** [comment]
Added to academy page, but need permissions to the google drive so that I can change/add some of the images.....and dang it did not have many academy pictures in that gallery.  Form was added and it emails to Coach Simon.

**Comment by paysl-johnl** [comment]
@paysl-briang Nice! I created a new Academy image for their page. I show two of the younger players in their light blue away uniforms. Even though they all wear the same uniforms, it figured it looks nice at first glance to see the younger academy kids in light blue and then the older select kids in dark blue.
